namespace Ledger.SyncServer.LoadTests;

/// Builds synthetic push batches matching exactly what the server actually
/// requires (see `EventsEndpoints.PushAsync`): a JSON array where every
/// element has a non-empty "eventId" — everything else is opaque payload
/// the server never inspects. No dependency on the domain project's real
/// event shape, because the server genuinely doesn't care what one looks
/// like (see the main README's "Why this server doesn't need to
/// understand the ledger's domain").
internal static class EventPayloads
{
    /// A batch of <paramref name="count"/> events, each with a fresh,
    /// globally-unique eventId (a GUID) so repeated load-test iterations
    /// never collide with an earlier run's already-stored events.
    public static object[] Batch(int count) =>
        Enumerable
            .Range(0, count)
            .Select(_ => new
            {
                eventId = Guid.NewGuid().ToString(),
                eventType = "loadtest.synthetic",
                payload = new { note = "generated by Ledger.SyncServer.LoadTests" },
            })
            .Cast<object>()
            .ToArray();
}
